### ISSUE TITLE
feature request, pls do a version for this as well

### ISSUE THREAD

**Issue by kolinfluence** [go-skynet/go-llama.cpp#102]
feature request, pls do a version for this as well
github.com/LostRuins/koboldcpp

thx

**Comment by mudler** [comment]
I don't think it really fits. This is a binding repository, not a full blown project like kobold.

By the way what's the difference  with https://github.com/go-skynet/LocalAI/tree/master ? At a glance kobold supports less backends, and LocalAI provides already a compatible OpenAI API endpoint.

**Comment by mudler** [comment]
Closing, not really anything we can do here.
