### ISSUE TITLE
Reverse prompt

### ISSUE THREAD

**Issue by normen** [go-skynet/go-llama.cpp#20]
Hi,

while I tried to implement chat-like answers in my LocalAI fork I noticed that the required `--reverse-prompt` option is missing in this binding..? To get proper chatgpt-like answers out of llama a "stop" for where the user adds input is needed.

Thanks for all this work!

**Comment by normen** [comment]
I made a shot at implementing this here: https://github.com/normen/go-llama.cpp/commit/23a81f1550166648bde526c0c0a7b9f5373d0873

I wasn't able to properly test it yet because I can't get the master of LocalAI working but it seems to work with the last version that doesn't have the gptj bindings included..

**Comment by normen** [comment]
Scratch that, it seems the reverse prompt option is only picked up on in interactive mode anyway... :/

**Comment by mudler** [comment]
true, thanks @normen !  good thoughts in here, I think we can still go with a stop word nevertheless, as that would help in any case to stop the answer at a certain point and pick it up from there again with other calls - as we keep all loaded in memory that shouldn't be much of a loss in performance

**Comment by mudler** [comment]
@normen slightly adapted your implementation to make it stop, thank you!

**Comment by mudler** [comment]
PR: https://github.com/go-skynet/go-llama.cpp/pull/21
