### ISSUE TITLE
how to get unbuffered responses?

### ISSUE THREAD

**Issue by BrunoIsaac27** [go-skynet/go-llama.cpp#4]
I noticed that .predict returns a complete string, which is the model's response. However, I need to give the user a feeling of iteration in which the model must send what it is "typing" in time to the user's client. But the .predict function only returns post-finished responses. How can I get an answer as predicted by the model? A feeling of "typing"

**Comment by mudler** [comment]
one way would be to restrict the binding to send back data directly to a golang channel, for instance: https://github.com/matiasinsaurralde/cgo-channels/tree/master however, I see still that could incur in a huge penalty, as context switch from golang and C in a loop have a high computational cost. 

I think we could offer a low-level functionality to address the specific case, but wouldn't suggest usage when performance is a requiremet.

**Comment by BrunoIsaac27** [comment]
> one way would be to restrict the binding to send back data directly to a golang channel, for instance: https://github.com/matiasinsaurralde/cgo-channels/tree/master however, I see still that could incur in a huge penalty, as context switch from golang and C in a loop have a high computational cost.
> 
> I think we could offer a low-level functionality to address the specific case and scope it to have just a few functions exposed, but wouldn't suggest usage when performance is a requirement.

can you create this functionality?

**Comment by noxer** [comment]
To answer the original question:
```go
llama.SetTokenCallback(func(token string) bool {
    fmt.Print(token)
    return true // we want the predictor to continue
})
```
