### ISSUE TITLE
How to properly import?

### ISSUE THREAD

**Issue by thedmdim** [go-skynet/go-llama.cpp#52]
Hello, thanks for your work, sincerely!

I wanna ask you how to use your package in my own program? As I understand i can't just do `import llama "github.com/go-skynet/go-llama.cpp"` in my code, can I? It needs compiling C due to llama.cpp code containing.

So my question is how to organize my Go repo, which will use your package?

**Comment by Aisuko** [comment]
Hi @thedmdim , I am not sure about if it is ok to import a go binding repo to another go repo but you can take a try and give feedback here. It is invaluable contribution.

**Comment by thedmdim** [comment]
@Aisuko , I think i found a way to use this binding in your own repo.

We will need Makefile in our repo with folowing:
1. We can include this binding as submodule OR simply do `git clone` into our repo
2. We need to build `./go-llama.cpp` in our repo
3. Then do `echo 'replace github.com/go-skynet/go-llama.cpp => ./go-llama.cpp' > go.mod`

The last step tells Go use not external `github.com/go-skynet/go-llama.cpp` but the `go-llama.cpp` which we cloned and built

I can't publish own example yet, but as soon as I release this I can to.
these repos helped me: https://github.com/go-skynet/go-llama.cpp/network/dependents
and this article helped me to figure out how things works:  https://softchris.github.io/golang-book/03-projects/03-create-shared-module/

**Comment by Aisuko** [comment]
> @Aisuko , I think i found a way to use this binding in your own repo.
> 
> We need Makefile in our repo with folowing:
> 
> 1. We can include this binding as submodule OR simply do `git clone` into our repo
> 2. We need to build `./go-llama.cpp` in our repo
> 3. Then do `echo 'replace github.com/go-skynet/go-llama.cpp => ./go-llama.cpp' > go.mod`
> 
> The last step tells Go use not external `github.com/go-skynet/go-llama.cpp` but the `go-llama.cpp` which we cloned and built
> 
> I can't publish own example yet, but as soon as I release this I can to. these repos helped me: https://github.com/go-skynet/go-llama.cpp/network/dependents and this article helped me to figure out how things works: https://softchris.github.io/golang-book/03-projects/03-create-shared-module/

Thanks for your feedback @thedmdim. Yes, we can use replace in `go.mod`. However, if you want to collaborate with more people, you should make sure all the people should have the same version `go-llama.cpp` in their local development environment. I believe you can fork `go-llama.cpp` to your own Github and development base on it.  For example, `replace github.com/go-skynet/go-llama.cpp => github.com/<your github address>/go-llama.cpp'`.
